[package]
name = "vl"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]
name = "vl"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "vl-cli"
path = "src/main.rs"


[dependencies]
clap = { version = "3.1", features = ["derive"] }
dirs = "4.0"

[build-dependencies]
serde_json = "1.0"
serde = "1.0"
convert_case = "0.5"
